DROP DATABASE IF EXISTS burgersDB; 

CREATE DATABASE burgersDB;

USE burgersDB;

CREATE TABLE burgers(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(225) NOT NULL,
    devoured BOOLEAN DEFAULT false,
    PRIMARY KEY (id)
);


